## Final Project :  Komputasi Genomik
### Name: Armand Faris A Surbakti
### NRP: 5023201051


### Import Libraries for Genomic Computation
#### After importing, open the fasta file first and read data

In [28]:
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqUtils import seq3
import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets
from IPython.display import display

In [29]:
fasta_file_path = "enterobacteria.fasta"
try:
    #Read the FASTA file using SeqIO.read
    record = SeqIO.read(fasta_file_path, "fasta")
    #Print the sequence record and its length
    print(str(record) + "\n")
    rec_seq = record.seq
    len_seq = print("Sequence Length = " + str(len(rec_seq)))
except FileNotFoundError:
    print(f"File not found: {fasta_file_path}")
except Exception as e:
    print(f"an error occurred: {e}")

ID: NC_001416.1
Name: NC_001416.1
Description: NC_001416.1 Enterobacteria phage lambda, complete genome
Number of features: 0
Seq('GGGCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCG...ACG')

Sequence Length = 48502


### Calculate Genome and Codon Statistics & Frequency

In [30]:
def DNAFrequency(A, C, G , T):
    count_A = 0
    count_C = 0
    count_G = 0
    count_T = 0
    noise = 0
    #iterarion for every character
    for char in rec_seq:
        if char == A:
            count_A += 1
        elif char == C:
            count_C += 1
        elif char == G:
            count_G += 1
        elif char == T:
            count_T += 1
        elif char != A or C or G or T:
            noise += 1
    total_A = print("Total DNA A = "+ str(count_A))
    total_C = print("Total DNA C = "+ str(count_C))
    total_G = print("Total DNA G = "+ str(count_G))
    total_T = print("Total DNA T = "+ str(count_T))
    total_noise = print("Total Noise/Error = "+ str(noise))
    print("\nTotal Frequency\n")
    print("Frequency A = " + str(count_A/(len(rec_seq)-noise)))
    print("Frequency C = " + str(count_C/(len(rec_seq)-noise)))
    print("Frequency G = " + str(count_G/(len(rec_seq)-noise)))
    print("Frequency T = " + str(count_T/(len(rec_seq)-noise)))
#call the dna frequency function
DNAFrequency('A', 'C', 'G', 'T')

Total DNA A = 12334
Total DNA C = 11362
Total DNA G = 12820
Total DNA T = 11986
Total Noise/Error = 0

Total Frequency

Frequency A = 0.2542987918023999
Frequency C = 0.23425838109768668
Frequency G = 0.2643189971547565
Frequency T = 0.24712382994515691


### Calculate Nucleotide and A-T C-G Density and Plotting them.

In [31]:
def a_content(seq, start, end):
    window = seq[start:end]
    if len(window) == 0:
        return 0
    a_count = 0
    for char in window:
        if char == 'A':
            a_count += 1
    return a_count / len(window)
def c_content(seq, start, end):
    window = seq[start:end]
    if len(window) == 0:
        return 0
    c_count = 0
    for char in window:
        if char == 'C':
            c_count += 1
    return c_count / len(window)
def g_content(seq, start, end):
    window = seq[start:end]
    if len(window) == 0:
        return 0
    g_count = 0
    for char in window:
        if char == 'G':
            g_count += 1
    return g_count / len(window)
def t_content(seq, start, end):
    window = seq[start:end]
    if len(window) == 0:
        return 0
    t_count = 0
    for char in window:
        if char == 'T':
            t_count += 1
    return t_count / len(window)
def gc_content(seq, start, end):
    window = seq[start:end]
    if len(window) == 0:
        return 0
    gc_count = 0
    for base in window:
        if base in ['G', 'C']:
            gc_count += 1
    return gc_count / len(window)
def at_content(seq, start, end):
    window = seq[start:end]
    if len(window) == 0:
        return 0
    at_count = 0
    for base in window:
        if base in ['A', 'T']:
            at_count += 1
    return at_count / len(window)
a_contents = []
c_contents = []
g_contents = []
t_contents = []
at_contents = []
gc_contents = []
#plotting the sliding window for GC content
def plot(wd):
    a_contents.clear()
    c_contents.clear()
    g_contents.clear()
    t_contents.clear()
    at_contents.clear()
    gc_contents.clear()
    for i in range(0, len(rec_seq) + 1, 5000):
        a_contents.append(a_content(rec_seq, i, i + wd))
        c_contents.append(c_content(rec_seq, i, i + wd))
        g_contents.append(g_content(rec_seq, i, i + wd))
        t_contents.append(t_content(rec_seq, i, i + wd))
        gc_contents.append(gc_content(rec_seq, i, i + wd))
        at_contents.append(at_content(rec_seq, i, i + wd))
    #x = np.arange(0, len(a_contents)/10, 0.1)
    x = np.linspace(0, len(rec_seq)/10**6, len(a_contents))
    #plotting function
    fig, ax = plt.subplots(2, figsize=(10,10))
    ax[0].set_title("Nucleotide Density")
    ax[0].set_xlabel("x10^6")
    ax[0].set_ylabel("Frequency")
    ax[0].plot(x, a_contents, label='A')
    ax[0].plot(x, c_contents, label='C')
    ax[0].plot(x, g_contents, label='G')
    ax[0].plot(x, t_contents, label='T')
    ax[0].set_xlim(0, len(rec_seq)/10**6)
    ax[0].legend()
    ax[0].grid()
    ax[1].set_title("A–T C–G Density")
    ax[1].set_xlabel("x10^6")
    ax[1].set_ylabel("Frequency")
    ax[1].plot(x, gc_contents, label='G-C')
    ax[1].plot(x, at_contents, label='A-T')
    ax[1].set_xlim(0, len(rec_seq)/10**6)
    ax[1].legend()
    ax[1].grid()
    return plt.show()
wd= widgets.IntText(value= 90000, description='Window Size : ')
widgets.interact_manual(plot, wd=wd)

interactive(children=(IntText(value=90000, description='Window Size : '), Button(description='Run Interact', s…

<function __main__.plot(wd)>

### ORF Program

In [38]:
k = int(input("Minimum Length: "))
print("Minimum Length:", k)
def find_orfs(dna, frame):
    orfs = []
    for start in range(frame, len(dna) - 2, 3):
        codon = dna[start:start + 3]
        if codon == "ATG":
            for stop in range(start + 3, len(dna), 3):
                if dna[stop:stop + 3] in ["TAA", "TAG", "TGA"]:
                    orf = dna[start:stop + 3]
                    if len(orf) > k:
                        orfs.append((orf, start + 1, stop + 3, frame))
                    break
    return orfs
def print_orfs(orfs, frame_type):
    count_t = 0
    for orf, start, stop, frame in orfs:
        count_t += 1
        print(f"Frame Type: {frame_type}{frame + 1} Start: {start} Stop: {stop}\nLength: {len(orf)}\nORF[{count_t}] {orf}\n")
    return count_t
dna = str(rec_seq.upper())
# Positive frames
positive_orfs = sum((find_orfs(dna, i) for i in range(3)), [])
positive_count = print_orfs(positive_orfs, '+')
# Negative frames
reverse_complement = dna[::-1].translate(str.maketrans("ATGC", "TACG"))
negative_orfs = sum((find_orfs(reverse_complement, i) for i in range(3)), [])
negative_count = print_orfs(negative_orfs, '-')
total_orfs = positive_count + negative_count
print("Total ORFs Found:", total_orfs)

Minimum Length: 75
Frame Type: +1 Start: 814 Stop: 894
Length: 81
ORF[1] ATGCTAATTACTATCTCCCGAAAGAATCCGCATACCAGGAAGGGCGCTGGGAAACACTGCCCTTTCAGCGGGCCATCATGA

Frame Type: +1 Start: 1165 Stop: 1362
Length: 198
ORF[2] ATGGGCGTGGCTTCTGGTGCCTGGGCGGTAAAGCGGCAAAAAACTACCGTGAAAAGTCGGTGGATGTGGCGGGTTATGATGAACTTGCTGCTTTTGATGATGATATTGAACAGGAAGGCTCTCCGACGTTCCTGGGTGACAAGCGTATTGAAGGCTCGGTCTGGCCAAAGTCCATCCGTGGCTCCACGCCAAAAGTGA

Frame Type: +1 Start: 1228 Stop: 1362
Length: 135
ORF[3] ATGTGGCGGGTTATGATGAACTTGCTGCTTTTGATGATGATATTGAACAGGAAGGCTCTCCGACGTTCCTGGGTGACAAGCGTATTGAAGGCTCGGTCTGGCCAAAGTCCATCCGTGGCTCCACGCCAAAAGTGA

Frame Type: +1 Start: 1240 Stop: 1362
Length: 123
ORF[4] ATGATGAACTTGCTGCTTTTGATGATGATATTGAACAGGAAGGCTCTCCGACGTTCCTGGGTGACAAGCGTATTGAAGGCTCGGTCTGGCCAAAGTCCATCCGTGGCTCCACGCCAAAAGTGA

Frame Type: +1 Start: 1243 Stop: 1362
Length: 120
ORF[5] ATGAACTTGCTGCTTTTGATGATGATATTGAACAGGAAGGCTCTCCGACGTTCCTGGGTGACAAGCGTATTGAAGGCTCGGTCTGGCCAAAGTCCATCCGTGGCTCCACGCCAAAAGTGA

Frame Type: +1 Start: 1261 Stop:

### ORF Testing

In [33]:
def translate_sequence(sequence):
    return seq3(str(Seq(sequence).translate()))
def orf_test(k):
    dna = str(rec_seq.upper())
    print('==============================')
    print("Original DNA Sequence:")
    print('==============================')
    print(dna, '\n')
    print("Reading Frames:")
    print('==============================')
    for i in range(3):
        frame = dna[i:]
        orf_sequence = find_orfs(frame, 0)[0][0]
        amino_acids = translate_sequence(orf_sequence)
        print(f"Frame {i + 1} - DNA: {orf_sequence}")
        print(f"Frame {i + 1} - Amino Acids: {amino_acids}\n")
    print()
    inv = str(dna[::-1])
    inv = inv.translate(str.maketrans("ATGC", "TACG"))
    print('==============================')
    print("Reverse Complement:")
    print(inv, '\n')
    print('==============================')
    print("Reading Frames (Reverse Complement):")
    print('==============================')
    for i in range(3):
        frame = inv[i:]
        orf_sequence = find_orfs(frame, 0)[0][0]
        amino_acids = translate_sequence(orf_sequence)
        print(f"Frame {i + 1} - DNA: {orf_sequence}")
        print(f"Frame {i + 1} - Amino Acids: {amino_acids}\n")
        print('=====================================')
    print()
k = 4
orf_test(k)

Original DNA Sequence:
GGGCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCGTTTCCGTTCTTCTTCGTCATAACTTAATGTTTTTATTTAAAATACCCTCTGAAAAGAAAGGAAACGACAGGTGCTGAAAGCGAGGCTTTTTGGCCTCTGTCGTTTCCTTTCTCTGTTTTTGTCCGTGGAATGAACAATGGAAGTCAACAAAAAGCAGCTGGCTGACATTTTCGGTGCGAGTATCCGTACCATTCAGAACTGGCAGGAACAGGGAATGCCCGTTCTGCGAGGCGGTGGCAAGGGTAATGAGGTGCTTTATGACTCTGCCGCCGTCATAAAATGGTATGCCGAAAGGGATGCTGAAATTGAGAACGAAAAGCTGCGCCGGGAGGTTGAAGAACTGCGGCAGGCCAGCGAGGCAGATCTCCAGCCAGGAACTATTGAGTACGAACGCCATCGACTTACGCGTGCGCAGGCCGACGCACAGGAACTGAAGAATGCCAGAGACTCCGCTGAAGTGGTGGAAACCGCATTCTGTACTTTCGTGCTGTCGCGGATCGCAGGTGAAATTGCCAGTATTCTCGACGGGCTCCCCCTGTCGGTGCAGCGGCGTTTTCCGGAACTGGAAAACCGACATGTTGATTTCCTGAAACGGGATATCATCAAAGCCATGAACAAAGCAGCCGCGCTGGATGAACTGATACCGGGGTTGCTGAGTGAATATATCGAACAGTCAGGTTAACAGGCTGCGGCATTTTGTCCGCGCCGGGCTTCGCTCACTGTTCAGGCCGGAGCCACAGACCGCCGTTGAATGGGCGGATGCTAATTACTATCTCCCGAAAGAATCCGCATACCAGGAAGGGCGCTGGGAAACACTGCCCTTTCAGCGGGCCATCATGAATGCGATGGGCAGCGACTACATCCGTGAGGTGAATGTGGTGAAGTCTGCCCGTGTCGGTTATTCCAAAATGCTGCTGGGTGTT

### HMM Implementation and Initialization

### Implement HMM with selected fasta file. Apply to a small section of the sequence for testing

In [34]:
def trans_state(input):
    if isinstance(input, float):
        #If input is a single float value, convert it to a list
        return ['HIGH' if input == 0 else 'LOW']
    else:
        #If input is already iterable, process it as usual
        return ['HIGH' if i == 0 else 'LOW' for i in input]
#Function to translate DNA base to observation state
def trans_obs(input):
    if input == 'A':
        output = 0
    elif input == 'T':
        output = 1
    elif input == 'G':
        output = 2
    elif input == 'C':
        output = 3
    return output
#function for the forward algorithm in HMM
def forward(obs_seq, a, b ,pi):
    N = len(a)
    T = len(obs_seq)
    forward = np.zeros((N, T))
    forwardprob = 0    
    for s in range(N):
        forward[s,0] = pi[s] * b[obs_seq[0], s]
    for i, t in enumerate(obs_seq[1:], 1):
        for s in range(N):
            for si in range(N):
                forward[s, i] += forward[si, i] * a[si, s] * b[t, s]
    for s in range(N):
       forwardprob += forward[s, T-1]
    return forwardprob
#function to run the Viterbi algorithm in HMM
def viterbi(obs_seq, a, b, pi):
    N = len(a)
    T = len(obs_seq)
    vtb = np.zeros((N, T))
    backpointer = np.zeros((N, T))
    for s in range(N):
        vtb[s, 0] = pi[s] * b[obs_seq[0], s]
    for i, t in enumerate(obs_seq[1:], 1):
        for s in range(N):
            count = np.zeros(2)
            for si in range(N):
                count[si] =  vtb[si, i-1] * a[si, s] * b[t, s]
            vtb[s, i] = np.max(count)
            backpointer[s, i-1] = np.argmax(count)
    count = np.zeros(N)
    for s in range(N):
        count[s] = vtb[s, -1]
    bestpathprob = np.max(count)
    bestpathpointer = np.argmax(count)
    bestpath = backpointer[bestpathpointer, :]
    bestpath = trans_state(bestpath)
    return bestpath, bestpathprob

In [35]:
def trans_state_to_obs(input):
    return 0 if input == 1 else 1
def run_hmm(file_path, threshold):
    try:
        record = SeqIO.read(file_path, "fasta")
        rec_seq = record.seq
        len_seq = len(rec_seq)
        # Calculate GC content in a sliding window
        gc_content_seq = [gc_content(rec_seq, i, i + 90000) for i in range(0, len_seq + 1, 5000)]
        # Translate GC content to observation states
        obs_seq = np.array([trans_obs('G') if gc > threshold else trans_obs('C') for gc in gc_content_seq], dtype=np.int16)
        a = np.array([[0.5, 0.5], [0.5, 0.5]])
        b = np.array([[0.1, 0.9], [0.1, 0.9], [0.9, 0.1], [0.9, 0.1]])
        pi = np.array([0.1, 0.9])
        #Run HMM
        forward_prob = forward(obs_seq, a, b, pi)
        print("Forward Probability:", forward_prob)
        start_prob_map_size = pi.shape
        transition_prob = a
        print("Transition Probability Matrix:\n", transition_prob)
        transition_prob_map_size = a.shape
        path, viterbi_prob = viterbi(obs_seq, a, b, pi)
        print("Viterbi Probability:", viterbi_prob)
        emission_prob = b
        print("Emission Probability Matrix:\n", emission_prob)
        emission_prob_map_size = b.shape
        print("Hidden State Sequences:")
        for i, j in zip(str(rec_seq), path):
            print('O : {} | S : {}'.format(i, j))
        freq_hidden_state = np.bincount(np.array([trans_state_to_obs(state) for state in path]))
        freq_hidden_state = freq_hidden_state / len(path)
        print("Frequency of Hidden States (LOW, HIGH):", freq_hidden_state)
        return start_prob_map_size, transition_prob, transition_prob_map_size, viterbi_prob, emission_prob, emission_prob_map_size
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred: {e}")
    return None
file_path_widget = widgets.Text(value="enterobacteria.fasta", description="File Path:")
threshold_widget = widgets.FloatSlider(value=0.5, min=0, max=1, step=0.01, description="Threshold:")
run_button = widgets.Button(description="Run HMM")
def on_button_click(b):
    file_path = file_path_widget.value
    threshold = threshold_widget.value
    run_hmm(file_path, threshold)
run_button.on_click(on_button_click)
widgets.VBox([file_path_widget, threshold_widget, run_button])

Forward Probability: 0.0
Transition Probability Matrix:
 [[0.5 0.5]
 [0.5 0.5]]
Viterbi Probability: 6.810125783203128e-05
Emission Probability Matrix:
 [[0.1 0.9]
 [0.1 0.9]
 [0.9 0.1]
 [0.9 0.1]]
Hidden State Sequences:
O : G | S : HIGH
O : G | S : HIGH
O : G | S : HIGH
O : C | S : HIGH
O : G | S : HIGH
O : G | S : HIGH
O : C | S : HIGH
O : G | S : HIGH
O : A | S : HIGH
O : C | S : HIGH
Frequency of Hidden States (LOW, HIGH): [0. 1.]


### Run HMM to the Whole Sequence

In [36]:
def run_hmm_whole_sequence(file_path, threshold):
    try:
        record = SeqIO.read(file_path, "fasta")
        rec_seq = record.seq
        len_seq = len(rec_seq)
        obs_seq = np.array([trans_obs(base) for base in rec_seq], dtype=np.int16)
        a = np.array([[0.5, 0.5], [0.5, 0.5]])
        b = np.array([[0.1, 0.9], [0.1, 0.9], [0.9, 0.1], [0.9, 0.1]])
        pi = np.array([0.1, 0.9])
        forward_prob = forward(obs_seq, a, b, pi)
        print("Forward Probability:", forward_prob)
        start_prob_map_size = pi.shape
        transition_prob = a
        print("Transition Probability Matrix:\n", transition_prob)
        transition_prob_map_size = a.shape
        path, viterbi_prob = viterbi(obs_seq, a, b, pi)
        print("Viterbi Probability:", viterbi_prob)
        emission_prob = b
        print("Emission Probability Matrix:\n", emission_prob)
        emission_prob_map_size = b.shape
        print("Hidden State Sequences:")
        for i, j in zip(str(rec_seq), path):
            print('O : {} | S : {}'.format(i, j))
        freq_hidden_state = np.bincount(np.array([trans_state_to_obs(state) for state in path]))
        freq_hidden_state = freq_hidden_state / len(path)
        print("Frequency of Hidden States (LOW, HIGH):", freq_hidden_state)
        return start_prob_map_size, transition_prob, transition_prob_map_size, viterbi_prob, emission_prob, emission_prob_map_size
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred: {e}")
    return None
file_path_widget = widgets.Text(value="enterobacteria.fasta", description="File Path:")
threshold_widget = widgets.FloatSlider(value=0.5, min=0, max=1, step=0.01, description="Threshold:")
run_button = widgets.Button(description="Run HMM")
def on_button_click(b):
    file_path = file_path_widget.value
    threshold = threshold_widget.value
    run_hmm_whole_sequence(file_path, threshold)
run_button.on_click(on_button_click)
widgets.VBox([file_path_widget, threshold_widget, run_button])

Forward Probability: 0.0
Transition Probability Matrix:
 [[0.5 0.5]
 [0.5 0.5]]
Viterbi Probability: 0.0
Emission Probability Matrix:
 [[0.1 0.9]
 [0.1 0.9]
 [0.9 0.1]
 [0.9 0.1]]
Hidden State Sequences:
O : G | S : HIGH
O : G | S : HIGH
O : G | S : HIGH
O : C | S : HIGH
O : G | S : HIGH
O : G | S : HIGH
O : C | S : HIGH
O : G | S : HIGH
O : A | S : LOW
O : C | S : HIGH
O : C | S : HIGH
O : T | S : LOW
O : C | S : HIGH
O : G | S : HIGH
O : C | S : HIGH
O : G | S : HIGH
O : G | S : HIGH
O : G | S : HIGH
O : T | S : LOW
O : T | S : LOW
O : T | S : LOW
O : T | S : LOW
O : C | S : HIGH
O : G | S : HIGH
O : C | S : HIGH
O : T | S : LOW
O : A | S : LOW
O : T | S : LOW
O : T | S : LOW
O : T | S : LOW
O : A | S : LOW
O : T | S : LOW
O : G | S : HIGH
O : A | S : LOW
O : A | S : LOW
O : A | S : LOW
O : A | S : LOW
O : T | S : LOW
O : T | S : LOW
O : T | S : LOW
O : T | S : LOW
O : C | S : HIGH
O : C | S : HIGH
O : G | S : HIGH
O : G | S : HIGH
O : T | S : LOW
O : T | S : LOW
O : T | S : LOW
O : 